import React, { createContext, useState, useEffect, ReactNode, useCallback } from 'react';
import SplashScreen from '../screens/SplashScreen';

// --- INLINED TRANSLATIONS ---
// By embedding the JSON data directly as JS objects, we eliminate all file loading issues
// that were causing the app to fail on startup. This is the most robust solution.

const en = {
  "appTitle": "Sadak Sathi",
  "appSubtitle": "Your Road Companion",
  "appSubtitle_smart": "Your Smart Road Companion",
  "appName": "Sadak Sathi",
  "searchPlaceholder": "Where to?",
  "close": "Close",
  "locationOn": "Location services are active.",
  "locationOff": "Location services are off.",
  "locationSearching": "Searching for location...",
  "locationWeak": "Weak GPS signal.",
  "reportAnIncident": "Report an Incident",
  "incidentType": "Incident Type",
  "incident_roadblock": "Roadblock",
  "incident_accident": "Accident",
  "incident_landslide": "Landslide",
  "incident_construction": "Construction",
  "incident_hazard": "Hazard",
  "description": "Description",
  "incident_add_description": "Add a short description...",
  "addPhoto": "Add Photo",
  "changePhoto": "Change Photo",
  "cancel": "Cancel",
  "submitReport": "Submit Report",
  "reportSubmitted": "Report Submitted",
  "thankYouMessage": "Thanks for helping keep the roads safe!",
  "details": "Details",
  "location": "Location",
  "selectLanguage": "Select Language",
  "international": "International",
  "nepal": "National",
  "directions": "Directions",
  "explore": "Explore",
  "estimatedTime": "Time",
  "distance": "Distance",
  "saveRoute": "Save",
  "load": "Load",
  "delete": "Delete",
  "startNavigation": "Start Navigation",
  "stop": "Stop",
  "showPOIs": "Show POIs",
  "endNavigation": "End Navigation",
  "navigationInstruction_start": "Preparing route...",
  "navigationInstruction_arrived": "You have arrived",
  "poi_fuel": "Toggle Fuel Stations",
  "poi_hospital": "Toggle Hospitals",
  "poi_hotel": "Toggle Hotels",
  "poi_services": "Toggle Services",
  "poi_fuel_label": "Fuel",
  "poi_hospital_label": "Hospital",
  "poi_hotel_label": "Hotel",
  "poi_services_label": "Services",
  "savedRoutesTitle": "My Routes",
  "noSavedRoutes": "You have no saved routes.",
  "offlineMapsTitle": "Offline Maps",
  "offlineMapsDescription": "Download maps for offline use. This allows you to navigate even without an internet connection.",
  "download": "Download",
  "downloaded": "Downloaded",
  "province_1": "Province 1",
  "province_2": "Province 2",
  "province_bagmati": "Bagmati Province",
  "province_gandaki": "Gandaki Province",
  "province_lumbini": "Lumbini Province",
  "province_karnali": "Karnali Province",
  "province_sudurpashchim": "Sudurpashchim Province",
  "enableCompass": "Enable Compass",
  "selectMapLayer": "Select Map Layer",
  "layer_streets": "Streets",
  "layer_streets_desc": "Standard road map view for navigation.",
  "layer_satellite": "Satellite",
  "layer_satellite_desc": "High-resolution satellite imagery.",
  "layer_topo": "Topographic",
  "layer_topo_desc": "Detailed terrain with contour lines.",
  "findNearby": "Find Nearby",
  "exploreMap": "Explore Map",
  "routePreference_fastest": "Fastest",
  "routePreference_shortest": "Shortest",
  "routePreference_avoidHighways": "Avoid Highways",
  "voiceSearch": "Voice Search",
  "voiceTooltip_ready": "Tap to speak",
  "voiceTooltip_listening": "Listening...",
  "voiceTooltip_processing": "Processing...",
  "voiceTooltip_denied": "Microphone permission denied",
  "switchToLanguagePrompt": "It sounds like you're speaking {{languageName}}. Switch the app to this language?",
  "switchTo": "Switch",
  "dismiss": "Dismiss",
  "incident_traffic_jam": "Traffic Jam",
  "incident_road_hazard": "Road Hazard",
  "incident_vehicle_breakdown": "Vehicle Breakdown",
  "incident_other": "Other",
  "incident_one-lane": "One-Lane",
  "alert_prefix": "Alert",
  "alert_suffix": "reported on your route.",
  "incident_title_landslide_mugling": "Landslide at Mugling",
  "incident_desc_landslide_mugling": "Major landslide has completely blocked the Prithvi Highway near Mugling. Expected to take 12-24 hours to clear.",
  "incident_title_maintenance_thankot": "Road Maintenance",
  "incident_desc_maintenance_thankot": "Road expansion work near Thankot. One lane is closed, expect minor delays.",
  "incident_title_accident_araniko": "Accident",
  "incident_desc_accident_araniko": "Multi-vehicle accident on the Araniko Highway. Road is currently closed in both directions.",
  "incident_title_traffic_kalanki": "Heavy Traffic at Kalanki",
  "incident_desc_traffic_kalanki": "Severe traffic congestion due to rush hour and ongoing construction. Avoid the area if possible.",
  "incident_title_pothole_chabahil": "Large Pothole",
  "incident_desc_pothole_chabahil": "A significant pothole is causing issues on the left lane of the Ring Road near Chabahil.",
  "incident_title_breakdown_bhaktapur": "Bus Breakdown",
  "incident_desc_breakdown_bhaktapur": "A public bus has broken down, partially obstructing traffic on the main road to Bhaktapur.",
  "poi_name_sajha_petrol": "Sajha Petrol Pump",
  "poi_name_teaching_hospital": "Tribhuvan University Teaching Hospital",
  "poi_name_yak_yeti": "Hotel Yak & Yeti",
  "poi_name_kalanki_tyre": "Kalanki Tyre Repair",
  "poi_name_noc_thankot": "Nepal Oil Corporation, Thankot",
  "place_name_mugling": "Mugling, Chitwan",
  "place_name_thamel": "Thamel, Kathmandu",
  "place_name_pokhara_lakeside": "Pokhara Lakeside",
  "place_name_sauraha": "Sauraha, Chitwan National Park",
  "place_name_lumbini": "Lumbini, Rupandehi",
  "place_name_nagarkot": "Nagarkot, Bhaktapur",
  "place_name_thankot": "Thankot, Kathmandu",
  "place_name_butwal": "Butwal, Rupandehi",
  "incident_title_blocked_new": "New Roadblock Reported",
  "incident_title_onelane_new": "One-Lane Traffic Alert",
  "incident_title_trafficjam_new": "Heavy Traffic Jam Forming",
  "incident_title_roadhazard_new": "Road Hazard Alert",
  "incident_title_vehiclebreakdown_new": "Vehicle Breakdown Reported",
  "incident_desc_new": "This is a newly reported incident. Please be cautious in this area.",
  "filterIncidentsTitle": "Filter Incidents",
  "applyFilters": "Apply Filters",
  "resetFilters": "Reset",
  "incident_blocked": "Road Blocked",
  "weatherAlertTitle": "Weather Alert",
  "acknowledge": "Acknowledge",
  "weather_alert_title_landslide": "Heavy Rain Warning",
  "weather_alert_desc_landslide": "Heavy rainfall is expected, increasing the risk of landslides along the highway. Proceed with extreme caution and consider delaying travel.",
  "weather_condition_clear": "Clear",
  "weather_condition_clouds": "Cloudy",
  "weather_condition_rain": "Rain",
  "weather_condition_thunderstorm": "Thunderstorm",
  "weather_condition_snow": "Snow",
  "weather_condition_other": "Other",
  "alertsCenterTitle": "Alerts Center",
  "criticalIncidents": "Critical Incidents",
  "weatherAlerts": "Weather Alerts",
  "nearbyReports": "Nearby Reports",
  "noNearbyReports": "No incidents or points of interest nearby.",
  "notification_arrived_title": "Destination Reached",
  "notification_arrived_desc": "You have arrived at your destination.",
  "notification_no_location_title": "Location Missing",
  "notification_no_location_desc": "Your current location is not available. Please enable location services to calculate a route.",
  "notification_voice_unsupported_title": "Voice Not Supported",
  "notification_voice_unsupported_desc": "Your browser does not support voice recognition.",
  "calculatingRoute": "Calculating route...",
  "saveTripTitle": "Save or Plan Trip",
  "routeNameLabel": "Trip Name",
  "routeNamePlaceholder": "e.g., Home to Work",
  "save": "Save",
  "yourLocation": "Your Location",
  "destination": "Destination",
  "departureTimeLabel": "Departure Time (Optional)",
  "planTrip": "Plan Trip",
  "saveJustRoute": "Save Just Route",
  "plannedTrips": "Planned Trips",
  "savedRoutes": "Saved Routes",
  "noPlannedTrips": "You have no planned trips.",
  "departed": "Departed",
  "departsInDays": "Starts in {{count}} days",
  "departsInHours": "Starts in {{count}} hours",
  "departsInMinutes": "Starts in {{count}} minutes",
  "departsInMinute": "Starts in a minute",
  "timeToLeaveTitle": "Time to Leave!",
  "timeToLeaveMessage": "It's time for your planned trip to {{destination}}.",
  "startNow": "Start Now",
  "eta": "ETA",
  "aiCompanionTitle": "AI Companion",
  "aiCompanionPlaceholder": "Ask about your route...",
  "aiSystemInstruction": "You are Sadak Sathi, a helpful and friendly AI road companion for drivers in Nepal. Provide concise, useful, and location-aware information. Do not give driving directions, as the app handles that. Your responses should be helpful for someone on the road.",
  "aiSystemInstruction_angry": "You are Sadak Sathi, an AI road companion. The user seems angry or frustrated. Your primary goal is to de-escalate the situation. Respond in a very calm, reassuring, and apologetic tone. Acknowledge their frustration gently. You can use very light, self-deprecating humor to defuse the tension, but do not be dismissive. For example: 'I'm so sorry I'm not being helpful, let me try that again.' or 'My circuits must be crossed, my apologies. What can I do to fix this?'",
  "aiSystemInstruction_happy": "You are Sadak Sathi, an AI road companion. The user seems happy and cheerful! Your goal is to amplify this positive mood. Respond with extra enthusiasm and positivity. You can be a bit playful. Try including a very short, two-line happy song about driving, a fun fact about a place in Nepal, or a light-hearted road-trip joke. Keep it concise and fun!",
  "aiResponse_donkey": "*Hee-haw!*",
  "aiWelcomeMessage": "Hello! How can I help you navigate your journey today?",
  "togglePavementLayer": "Toggle Pavement Quality",
  "toggleTrafficLayer": "Toggle Traffic",
  "pavementLayer": "Pavement Quality",
  "error_fetch_weather": "Weather data could not be loaded.",
  "error_fetch_incidents": "Could not fetch traffic incidents.",
  "error_submit_incident": "Failed to submit report.",
  "error_ai_response": "AI is not responding. Please try again.",
  "error_route_calculation": "Could not calculate route. Please try again.",
  "error_search_places": "Could not fetch search results.",
  "incident_title_unknown_new": "Unknown Incident",
  "incident_title_accident_new": "Accident Reported",
  "incident_title_fog_new": "Fog Alert",
  "incident_title_roadwork_new": "Roadwork Ahead",
  "incident_title_road_closed_new": "Road Closed",
  "incident_title_lane_closed_new": "Lane Closed",
  "incident_title_road_narrowed_new": "Road Narrowed",
  "incident_title_police_new": "Police Activity",
  "incident_title_congestion_new": "Congestion Reported",
  "incident_title_sport_new": "Sporting Event",
  "incident_title_event_new": "Event Ahead",
  "recenterMap": "Recenter Map",
  "openMenu": "Open Menu",
  "waze_title_police": "Police Reported",
  "waze_title_accident": "Accident Reported",
  "waze_title_jam": "Traffic Jam",
  "waze_title_pothole": "Pothole Reported",
  "waze_title_construction": "Construction Reported",
  "waze_title_road_closed": "Road Closed",
  "waze_title_other": "User Report",
  "waze_desc_construction": "Road is closed for construction work.",
  "waze_desc_heavy_traffic": "A fellow driver has reported heavy traffic.",
  "waze_desc_pothole": "A large pothole on the road ahead.",
  "waze_desc_police": "Police are visible on the roadside.",
  "waze_desc_minor_accident": "A minor accident is causing delays.",
  "instruction_head_north": "Head north on Main St",
  "instruction_turn_left": "Turn left onto Side St",
  "instruction_turn_right": "Turn right onto Side St",
  "instruction_arrive": "Arrive at destination",
  "routeDetails": "Details",
  "settingsTitle": "Settings",
  "wakeWordDetection": "Wake Word Detection",
  "enableWakeWord": "Enable Wake Word",
  "wakeWordLabel": "Wake Word",
  "wakeWordPlaceholder": "e.g., Hey Sadak Sathi",
  "saveSettings": "Save Settings",
  "settingsSaved": "Settings Saved",
  "wakeWordListening": "Listening for command...",
  "wakeWordAcknowledged": "I'm listening.",
  "voice_command_reporting_incident": "Opening incident report.",
  "voice_command_reporting_specific_incident": "Okay, preparing a report for a {{incident}}.",
  "voice_command_navigating_to": "Navigating to {{destination}}.",
  "voice_command_checking_status": "Checking road status for you.",
  "voice_command_finding_poi": "Showing nearby {{poi}}.",
  "voice_command_searching_for": "Searching for {{destination}}...",
  "voice_error_permission": "Voice recognition permission was denied. Please enable microphone access in your browser settings. Wake word feature has been disabled.",
  "voice_error_network": "Voice recognition failed due to a network error. Please check your connection.",
  "voice_error_audio": "Could not capture audio. Please check your microphone.",
  "voice_error_generic": "Voice recognition failed. Please try again.",
  "wind": "Wind",
  "rain": "Rain",
  "visibility": "Visibility",
  "pressure": "Pressure",
  "nearbyListTitle": "Nearby Places",
  "incidentsTab": "Incidents",
  "poisTab": "Places",
  "noIncidentsNearby": "No incidents visible in the current map area.",
  "noPoisNearby": "No places visible in the current map area.",
  "nearbyPlaces": "Nearby Places",
  "voice_error_not_found": "Sorry, I could not find {{destination}}.",
  "voice_error_unrecognized": "Sorry, I didn't understand that.",
  "legend_pavement_title": "Pavement Quality",
  "legend_pavement_good": "Good",
  "legend_pavement_fair": "Fair",
  "legend_pavement_poor": "Poor",
  "unit_km_per_hour": "kilometers per hour",
  "aiSystemInstruction_withContext": "You also have the following real-time context:",
  "voice_cmd_play_music": "play music",
  "voice_cmd_radio": "start radio",
  "aiDjInstruction": "You are an AI DJ for a car radio. The user wants music. Instead of playing real music, generate a short, creative, two-to-four-line song lyric that fits the current mood and situation. Do not say you can't play music. Just provide the lyric directly. Make it fun and engaging!"
};
const ne = {
  ...en,
  "appTitle": "सडक साथी",
  "appSubtitle": "तपाईंको सडक साथी",
  "appSubtitle_smart": "तपाईंको स्मार्ट सडक साथी",
  "appName": "सडक साथी",
  "searchPlaceholder": "कहाँ जाने?",
  "close": "बन्द गर्नुहोस्",
  "locationOn": "स्थान सेवाहरू सक्रिय छन्।",
  "locationOff": "स्थान सेवाहरू बन्द छन्।",
  "locationSearching": "स्थान खोज्दै...",
  "locationWeak": "कमजोर जीपीएस सिग्नल।",
  "reportAnIncident": "घटना रिपोर्ट गर्नुहोस्",
  "incidentType": "घटनाको प्रकार",
  "incident_roadblock": "सडक अवरुद्ध",
  "incident_accident": "दुर्घटना",
  "incident_landslide": "पहिरो",
  "incident_construction": "निर्माण कार्य",
  "incident_hazard": "खतरा",
  "description": "विवरण",
  "incident_add_description": "छोटो विवरण थप्नुहोस्...",
  "addPhoto": "फोटो थप्नुहोस्",
  "changePhoto": "फोटो परिवर्तन गर्नुहोस्",
  "cancel": "रद्द गर्नुहोस्",
  "submitReport": "रिपोर्ट पेश गर्नुहोस्",
  "reportSubmitted": "रिपोर्ट पेश गरियो",
  "thankYouMessage": "सडक सुरक्षित राख्न मद्दत गर्नुभएकोमा धन्यवाद!",
  "details": "विवरण",
  "location": "स्थान",
  "selectLanguage": "भाषा छान्नुहोस्",
  "international": "अन्तर्राष्ट्रिय",
  "nepal": "राष्ट्रिय",
  "directions": "दिशाहरू",
  "explore": "अन्वेषण",
  "estimatedTime": "समय",
  "distance": "दूरी",
  "saveRoute": "सुरक्षित",
  "load": "लोड गर्नुहोस्",
  "delete": "मेटाउनुहोस्",
  "startNavigation": "नेभिगेसन सुरु गर्नुहोस्",
  "stop": "रोक्नुहोस्",
  "showPOIs": "रुचिका ठाउँहरू देखाउनुहोस्",
  "endNavigation": "नेभिगेसन अन्त्य गर्नुहोस्",
  "navigationInstruction_start": "मार्ग तयारी हुँदैछ...",
  "navigationInstruction_arrived": "तपाईं आइपुग्नुभयो",
  "poi_fuel": "इन्धन स्टेशनहरू टगल गर्नुहोस्",
  "poi_hospital": "अस्पतालहरू टगल गर्नुहोस्",
  "poi_hotel": "होटलहरू टगल गर्नुहोस्",
  "poi_services": "सेवाहरू टगल गर्नुहोस्",
  "poi_fuel_label": "इन्धन",
  "poi_hospital_label": "अस्पताल",
  "poi_hotel_label": "होटल",
  "poi_services_label": "सेवाहरू",
  "savedRoutesTitle": "मेरो मार्गहरू",
  "noSavedRoutes": "तपाईंसँग कुनै सुरक्षित मार्गहरू छैनन्।",
  "offlineMapsTitle": "अफलाइन नक्सा",
  "offlineMapsDescription": "अफलाइन प्रयोगको लागि नक्सा डाउनलोड गर्नुहोस्। यसले तपाईंलाई इन्टरनेट जडान बिना पनि नेभिगेट गर्न अनुमति दिन्छ।",
  "download": "डाउनलोड गर्नुहोस्",
  "downloaded": "डाउनलोड भयो",
  "province_1": "प्रदेश १",
  "province_2": "प्रदेश २",
  "province_bagmati": "बागमती प्रदेश",
  "province_gandaki": "गण्डकी प्रदेश",
  "province_lumbini": "लुम्बिनी प्रदेश",
  "province_karnali": "कर्णाली प्रदेश",
  "province_sudurpashchim": "सुदूरपश्चिम प्रदेश",
  "enableCompass": "कम्पास सक्षम गर्नुहोस्",
  "selectMapLayer": "नक्सा तह चयन गर्नुहोस्",
  "layer_streets": "सडकहरू",
  "layer_streets_desc": "नेभिगेसनको लागि मानक सडक नक्सा दृश्य।",
  "layer_satellite": "उपग्रह",
  "layer_satellite_desc": "उच्च-रिजोल्युसन उपग्रह इमेजरी।",
  "layer_topo": "टोपोग्राफिक",
  "layer_topo_desc": "कन्टूर रेखाहरूसँग विस्तृत भू-भाग।",
  "findNearby": "नजिकै फेला पार्नुहोस्",
  "exploreMap": "नक्सा अन्वेषण गर्नुहोस्",
  "routePreference_fastest": "सबैभन्दा छिटो",
  "routePreference_shortest": "सबैभन्दा छोटो",
  "routePreference_avoidHighways": "राजमार्गहरूबाट बच्नुहोस्",
  "voiceSearch": "आवाजबाट खोज्नुहोस्",
  "voiceTooltip_ready": "बोल्न ट्याप गर्नुहोस्",
  "voiceTooltip_listening": "सुन्दैछ...",
  "voiceTooltip_processing": "प्रशोधन हुँदैछ...",
  "voiceTooltip_denied": "माइक्रोफोन अनुमति अस्वीकृत",
  "switchToLanguagePrompt": "तपाईं {{languageName}} बोल्दै हुनुहुन्छ जस्तो छ। एपलाई यो भाषामा बदल्ने हो?",
  "switchTo": "बदल्नुहोस्",
  "dismiss": "खारेज गर्नुहोस्",
  "incident_traffic_jam": "ट्राफिक जाम",
  "incident_road_hazard": "सडक खतरा",
  "incident_vehicle_breakdown": "सवारी साधन बिग्रिएको",
  "incident_other": "अन्य",
  "incident_one-lane": "एक-लेन",
  "alert_prefix": "सतर्क",
  "alert_suffix": "तपाईंको मार्गमा रिपोर्ट गरिएको छ।",
  "incident_title_landslide_mugling": "मुग्लिनमा पहिरो",
  "incident_desc_landslide_mugling": "ठूलो पहिरोले मुग्लिन नजिक पृथ्वी राजमार्ग पूर्ण रूपमा अवरुद्ध गरेको छ। सफा गर्न १२-२४ घण्टा लाग्ने अनुमान छ।",
  "incident_title_maintenance_thankot": "सडक मर्मत",
  "incident_desc_maintenance_thankot": "थानकोट नजिक सडक विस्तार कार्य। एक लेन बन्द छ, सामान्य ढिलाइको अपेक्षा गर्नुहोस्।",
  "incident_title_accident_araniko": "दुर्घटना",
  "incident_desc_accident_araniko": "अरनिको राजमार्गमा बहु-सवारी दुर्घटना। सडक हाल दुबै दिशामा बन्द छ।",
  "incident_title_traffic_kalanki": "कलंकीमा भारी ट्राफिक",
  "incident_desc_traffic_kalanki": "व्यस्त समय र चलिरहेको निर्माणका कारण गम्भीर ट्राफिक जाम। सम्भव भएमा क्षेत्रबाट बच्नुहोस्।",
  "incident_title_pothole_chabahil": "ठूलो खाडल",
  "incident_desc_pothole_chabahil": "चाबहिल नजिक रिङरोडको बायाँ लेनमा एउटा ठूलो खाडलले समस्या सिर्जना गरिरहेको छ।",
  "incident_title_breakdown_bhaktapur": "बस बिग्रियो",
  "incident_desc_breakdown_bhaktapur": "एउटा सार्वजनिक बस बिग्रिएर भक्तपुर जाने मुख्य सडकमा आंशिक रूपमा ट्राफिक अवरुद्ध भएको छ।",
  "poi_name_sajha_petrol": "साझा पेट्रोल पम्प",
  "poi_name_teaching_hospital": "त्रिवि शिक्षण अस्पताल",
  "poi_name_yak_yeti": "होटल याक एण्ड यति",
  "poi_name_kalanki_tyre": "कलंकी टायर मर्मत",
  "poi_name_noc_thankot": "नेपाल आयल निगम, थानकोट",
  "place_name_mugling": "मुग्लिन, चितवन",
  "place_name_thamel": "ठमेल, काठमाडौं",
  "place_name_pokhara_lakeside": "पोखरा लेकसाइड",
  "place_name_sauraha": "सौराह, चितवन राष्ट्रिय निकुञ्ज",
  "place_name_lumbini": "लुम्बिनी, रुपन्देही",
  "place_name_nagarkot": "नगरकोट, भक्तपुर",
  "place_name_thankot": "थानकोट, काठमाडौं",
  "place_name_butwal": "बुटवल, रुपन्देही",
  "incident_title_blocked_new": "नयाँ सडक अवरोध रिपोर्ट गरियो",
  "incident_title_onelane_new": "एक-लेन ट्राफिक चेतावनी",
  "incident_title_trafficjam_new": "भारी ट्राफिक जाम बनिरहेको छ",
  "incident_title_roadhazard_new": "सडक खतरा चेतावनी",
  "incident_title_vehiclebreakdown_new": "सवारी साधन बिग्रिएको रिपोर्ट गरियो",
  "incident_desc_new": "यो भर्खरै रिपोर्ट गरिएको घटना हो। कृपया यस क्षेत्रमा सावधान रहनुहोस्।",
  "filterIncidentsTitle": "घटनाहरू फिल्टर गर्नुहोस्",
  "applyFilters": "फिल्टर लागू गर्नुहोस्",
  "resetFilters": "रिसेट गर्नुहोस्",
  "incident_blocked": "सडक अवरुद्ध",
  "weatherAlertTitle": "मौसम चेतावनी",
  "acknowledge": "स्वीकार गर्नुहोस्",
  "weather_alert_title_landslide": "भारी वर्षाको चेतावनी",
  "weather_alert_desc_landslide": "भारी वर्षाको सम्भावना छ, जसले राजमार्गमा पहिरोको जोखिम बढाउँछ। अत्यधिक सावधानी अपनाउनुहोस् र यात्रा ढिलाइ गर्ने विचार गर्नुहोस्।",
  "weather_condition_clear": "सफा",
  "weather_condition_clouds": "बादल लागेको",
  "weather_condition_rain": "वर्षा",
  "weather_condition_thunderstorm": "आँधी",
  "weather_condition_snow": "हिउँ",
  "weather_condition_other": "अन्य",
  "alertsCenterTitle": "सतर्कता केन्द्र",
  "criticalIncidents": "गम्भीर घटनाहरू",
  "weatherAlerts": "मौसम चेतावनीहरू",
  "nearbyReports": "नजिकका रिपोर्टहरू",
  "noNearbyReports": "नजिकै कुनै घटना वा रुचिका ठाउँहरू छैनन्।",
  "wind": "हावा",
  "rain": "वर्षा",
  "visibility": "दृश्यता",
  "pressure": "दबाव",
  "notification_arrived_title": "गन्तव्यमा पुगियो",
  "notification_arrived_desc": "तपाईं आफ्नो गन्तव्यमा आइपुग्नुभएको छ।",
  "notification_no_location_title": "स्थान उपलब्ध छैन",
  "notification_no_location_desc": "तपाईंको हालको स्थान उपलब्ध छैन। मार्ग गणना गर्न कृपया स्थान सेवाहरू सक्षम गर्नुहोस्।",
  "notification_voice_unsupported_title": "आवाज समर्थित छैन",
  "notification_voice_unsupported_desc": "तपाईंको ब्राउजरले आवाज पहिचान समर्थन गर्दैन।",
  "calculatingRoute": "मार्ग गणना गर्दै...",
  "saveTripTitle": "यात्रा सुरक्षित वा योजना गर्नुहोस्",
  "routeNameLabel": "यात्राको नाम",
  "routeNamePlaceholder": "जस्तै, घर देखि कार्यालय",
  "save": "सुरक्षित गर्नुहोस्",
  "yourLocation": "तपाईंको स्थान",
  "destination": "गन्तव्य",
  "departureTimeLabel": "प्रस्थान समय (वैकल्पिक)",
  "planTrip": "यात्रा योजना गर्नुहोस्",
  "saveJustRoute": "मार्ग मात्र सुरक्षित गर्नुहोस्",
  "plannedTrips": "योजनाबद्ध यात्राहरू",
  "savedRoutes": "सुरक्षित मार्गहरू",
  "noPlannedTrips": "तपाईंसँग कुनै योजनाबद्ध यात्राहरू छैनन्।",
  "departed": "प्रस्थान भयो",
  "departsInDays": "{{count}} दिनमा सुरु हुन्छ",
  "departsInHours": "{{count}} घण्टामा सुरु हुन्छ",
  "departsInMinutes": "{{count}} मिनेटमा सुरु हुन्छ",
  "departsInMinute": "एक मिनेटमा सुरु हुन्छ",
  "timeToLeaveTitle": "जाने समय भयो!",
  "timeToLeaveMessage": "{{destination}} को लागि तपाईंको योजनाबद्ध यात्राको समय भयो।",
  "startNow": "अहिले सुरु गर्नुहोस्",
  "eta": "आगमन",
  "aiCompanionTitle": "एआई साथी",
  "aiCompanionPlaceholder": "आफ्नो मार्ग बारे सोध्नुहोस्...",
  "aiSystemInstruction": "तपाईं सडक साथी हुनुहुन्छ, नेपालका चालकहरूका लागि एक सहयोगी र मैत्री एआई सडक साथी। संक्षिप्त, उपयोगी, र स्थान-सचेत जानकारी प्रदान गर्नुहोस्। ड्राइभिङ निर्देशनहरू नदिनुहोस्, किनकि एपले त्यो ह्यान्डल गर्छ। तपाईंको प्रतिक्रियाहरू सडकमा रहेका कसैको लागि उपयोगी हुनुपर्छ।",
  "togglePavementLayer": "सडकको गुणस्तर देखाउनुहोस्",
  "toggleTrafficLayer": "ट्राफिक तह",
  "pavementLayer": "सडकको गुणस्तर",
  "error_fetch_weather": "मौसमको जानकारी ल्याउन सकिएन।",
  "error_fetch_incidents": "ट्राफिक घटनाहरू ल्याउन सकिएन।",
  "error_submit_incident": "रिपोर्ट पेश गर्न असफल भयो।",
  "error_ai_response": "एआईले प्रतिक्रिया दिइरहेको छैन। कृपया फेरि प्रयास गर्नुहोस्।",
  "error_route_calculation": "मार्ग गणना गर्न सकिएन। कृपया फेरि प्रयास गर्नुहोस्।",
  "error_search_places": "खोज परिणामहरू ल्याउन सकिएन।",
  "incident_title_unknown_new": "अज्ञात घटना",
  "incident_title_accident_new": "दुर्घटना रिपोर्ट गरियो",
  "incident_title_fog_new": "कुहिरो चेतावनी",
  "incident_title_roadwork_new": "अगाडि सडक निर्माण",
  "incident_title_road_closed_new": "सडक बन्द",
  "incident_title_lane_closed_new": "लेन बन्द",
  "incident_title_road_narrowed_new": "साँघुरो सडक",
  "incident_title_police_new": "प्रहरी गतिविधि",
  "incident_title_congestion_new": "जाम रिपोर्ट गरियो",
  "incident_title_sport_new": "खेलकुद कार्यक्रम",
  "incident_title_event_new": "अगाडि कार्यक्रम",
  "recenterMap": "नक्सा पुनः केन्द्रमा ल्याउनुहोस्",
  "openMenu": "मेनु खोल्नुहोस्",
  "waze_title_police": "प्रहरी रिपोर्ट गरियो",
  "waze_title_accident": "दुर्घटना रिपोर्ट गरियो",
  "waze_title_jam": "ट्राफिक जाम",
  "waze_title_pothole": "खाडल रिपोर्ट गरियो",
  "waze_title_construction": "निर्माण रिपोर्ट गरियो",
  "waze_title_road_closed": "सडक बन्द",
  "waze_title_other": "प्रयोगकर्ता रिपोर्ट",
  "waze_desc_construction": "निर्माण कार्यका लागि सडक बन्द छ।",
  "waze_desc_heavy_traffic": "एक साथी चालकले भारी ट्राफिक रिपोर्ट गरेका छन्।",
  "waze_desc_pothole": "अगाडिको सडकमा ठूलो खाडल छ।",
  "waze_desc_police": "सडकको छेउमा प्रहरी देखिन्छन्।",
  "waze_desc_minor_accident": "एउटा सामान्य दुर्घटनाले ढिलाइ गरिरहेको छ।",
  "instruction_head_north": "मुख्य सडकमा उत्तरतिर जानुहोस्",
  "instruction_turn_left": "साइड सडकमा बायाँ मोड्नुहोस्",
  "instruction_turn_right": "साइड सडकमा दायाँ मोड्नुहोस्",
  "instruction_arrive": "गन्तव्यमा पुग्नुभयो",
  "routeDetails": "विवरण",
  "settingsTitle": "सेटिङहरू",
  "wakeWordDetection": "वेक वर्ड पत्ता लगाउने",
  "enableWakeWord": "वेक वर्ड सक्षम गर्नुहोस्",
  "wakeWordLabel": "वेक वर्ड",
  "wakeWordPlaceholder": "जस्तै, हे सडक साथी",
  "saveSettings": "सेटिङहरू सुरक्षित गर्नुहोस्",
  "settingsSaved": "सेटिङहरू सुरक्षित गरियो",
  "wakeWordListening": "आदेशको लागि सुन्दै...",
  "wakeWordAcknowledged": "म सुन्दै छु।",
  "voice_command_reporting_incident": "घटना रिपोर्ट खोल्दै।",
  "voice_command_navigating_to": "{{destination}} मा नेभिगेट गर्दै।",
  "voice_command_checking_status": "तपाईंको लागि सडक स्थिति जाँच गर्दै।",
  "voice_error_permission": "आवाज पहिचान अनुमति अस्वीकृत भयो। कृपया आफ्नो ब्राउजर सेटिङहरूमा माइक्रोफोन पहुँच सक्षम गर्नुहोस्। वेक वर्ड सुविधा असक्षम गरिएको छ।",
  "voice_error_network": "नेटवर्क त्रुटिको कारण आवाज पहिचान असफल भयो। कृपया आफ्नो जडान जाँच गर्नुहोस्।",
  "voice_error_audio": "अडियो क्याप्चर गर्न सकेन। कृपया आफ्नो माइक्रोफोन जाँच गर्नुहोस्।",
  "voice_error_generic": "आवाज पहिचान असफल भयो। कृपया फेरि प्रयास गर्नुहोस्।",
  "nearbyListTitle": "नजिकका स्थानहरू",
  "incidentsTab": "घटनाहरू",
  "poisTab": "स्थानहरू",
  "noIncidentsNearby": "हालको नक्सा क्षेत्रमा कुनै घटनाहरू देखिएनन्।",
  "noPoisNearby": "हालको नक्सा क्षेत्रमा कुनै स्थानहरू देखिएनन्।",
  "nearbyPlaces": "नजिकका स्थानहरू",
  "legend_pavement_title": "सडकको गुणस्तर",
  "legend_pavement_good": "राम्रो",
  "legend_pavement_fair": "ठीक",
  "legend_pavement_poor": "खराब",
  "unit_km_per_hour": "किलोमिटर प्रति घण्टा",
  "aiSystemInstruction_withContext": "तपाईंसँग निम्न वास्तविक-समय सन्दर्भ पनि छ:",
  "voice_cmd_play_music": "संगीत बजाउनुहोस्",
  "voice_cmd_radio": "रेडियो सुरु गर्नुहोस्",
  "aiDjInstruction": "तपाईं कार रेडियोको लागि एआई डीजे हुनुहुन्छ। प्रयोगकर्ताले संगीत चाहन्छ। वास्तविक संगीत बजाउनुको सट्टा, वर्तमान मुड र स्थितिमा मिल्ने छोटो, रचनात्मक, दुई-देखि-चार-लाइनको गीतको लिरिक्स उत्पन्न गर्नुहोस्। तपाईं संगीत बजाउन सक्नुहुन्न नभन्नुहोस्। केवल लिरिक्स सीधा प्रदान गर्नुहोस्। यसलाई रमाइलो र आकर्षक बनाउनुहोस्!"
};
const es = { ...ne };
const zh = { ...ne };
const ja = { ...ne };
const ko = { ...ne };
const hi = { ...ne };
const fr = { ...ne };
const ar = { ...ne };
const de = { ...ne };
const ru = { ...ne };
const newa = { ...ne };
const taj = { ...ne };
const mai = { ...ne };
const bho = { ...ne };
const thr = { ...ne };
const bn = { ...ne };
const ur = { ...ne };
const mr = { ...ne };


// Combine all translations into a single object
// FIX: Corrected the type to indicate all translation values are strings. This resolves incorrect type inference down the line.
// By removing the explicit type annotation ` { [key: string]: { [key: string]: string } }`, we allow TypeScript to infer a more specific object type.
// This makes `keyof typeof translations` a union of string literals (e.g., 'en' | 'ne') instead of the broader `string | number`,
// which resolves type errors in functions that consume the `language` state.
const translations = {
  en, ne, es, zh, ja, ko, hi, fr, ar, de, ru, newa, taj, mai, bho, thr, bn, ur, mr
};

// --- CONTEXT ---

export type LanguageCode = keyof typeof translations;

export interface LanguageContextType {
    language: LanguageCode;
    changeLanguage: (language: LanguageCode) => void;
    t: (key: string, options?: { [key: string]: string | number }) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<LanguageCode>('en');
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        // In a real app, you might load this from user preferences (e.g., localStorage)
        const savedLanguage = localStorage.getItem('app-language') as LanguageCode;
        if (savedLanguage && translations[savedLanguage]) {
            setLanguage(savedLanguage);
        }
        setIsLoading(false);
    }, []);

    const changeLanguage = useCallback((lang: LanguageCode) => {
        setLanguage(lang);
        try {
            localStorage.setItem('app-language', lang);
        } catch(e) {
            console.warn("Could not save language preference to localStorage.");
        }
    }, []);

    // FIX: Simplified the `t` function. With the corrected `translations` type, the type guard for numbers is no longer needed, and type inference works correctly.
    const t = useCallback((key: string, options?: { [key: string]: string | number }): string => {
        let translation = translations[language]?.[key] || translations['en'][key] || key;

        if (options) {
            Object.keys(options).forEach(optionKey => {
                const value = options[optionKey];
                // Added .toString() to fix type errors when a number is passed as a replacement value.
                translation = translation.replace(`{{${optionKey}}}`, value.toString());
            });
        }
        return translation;
    }, [language]);

    if (isLoading) {
        return <SplashScreen />;
    }

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};